name: Android Build APK

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug
          dependency-graph: generate-and-submit
          artifact-retention-days: 7
      - name: Push release
        run: |
          git init
          git config user.name "github-actions"
          git config user.email "41898282+github-actions@users.noreply.github.com"
          git remote add origin "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}"
          git checkout -b apk
          git add *.apk
          git commit -m "Build debug APK for $GITHUB_SHA"
          git push -f -u origin apk
        working-directory: app/build/outputs/apk/debug
